FILE(MAKE_DIRECTORY "/home/leo/decision_pkg/devel/share/patrol/graphs" )
FILE(GLOB_RECURSE FOR_DEL /home/leo/decision_pkg/devel/share/patrol/graphs/* )
#message("delete files from /home/leo/decision_pkg/devel/share/patrol/graphs/ : ${FOR_DEL}")
if( FOR_DEL )
	FILE(REMOVE ${FOR_DEL})
endif()
execute_process(COMMAND /lib/decision_making_parser/decision_making_parser -pe -xml -dot -src "/home/leo/decision_pkg/src/patrol" -dst "/home/leo/decision_pkg/devel/share/patrol/graphs" -f "/home/leo/decision_pkg/src/patrol/src/patrolNode.cpp:" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/leo/decision_pkg/devel/share/patrol/graphs/ /home/leo/decision_pkg/devel/share/patrol/graphs/*.scxml /home/leo/decision_pkg/devel/share/patrol/graphs/*.btxml  /home/leo/decision_pkg/devel/share/patrol/graphs/*.taoxml)
message("   -- Created XML files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/leo/decision_pkg/devel/share/patrol/graphs/*.scxml /home/leo/decision_pkg/devel/share/patrol/graphs/*.btxml /home/leo/decision_pkg/devel/share/patrol/graphs/*.taoxml)
execute_process(COMMAND "python" /lib/decision_making_parser/decision_making_xml_parser.py -i "/home/leo/decision_pkg/src/patrol" "/home/leo/decision_pkg/devel/share/patrol/graphs" "${CREATED_FILES_ABS}" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/leo/decision_pkg/devel/share/patrol/graphs/ /home/leo/decision_pkg/devel/share/patrol/graphs/*.dot /home/leo/decision_pkg/devel/share/patrol/graphs/*.xot)
message("   -- Created DOT files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/leo/decision_pkg/devel/share/patrol/graphs/*.dot)
foreach( f ${CREATED_FILES_ABS} )
	execute_process(COMMAND "dot" -q1 -Tgif -o${f}.gif  ${f} RESULT_VARIABLE rv)
endforeach()
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/leo/decision_pkg/devel/share/patrol/graphs/ /home/leo/decision_pkg/devel/share/patrol/graphs/*.gif)
message("   -- Created GIF files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
